import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google"; // Fixed import
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import { CartSync } from "@/components/cart/cart-sync";
import { Toaster } from "@/components/ui/sonner";
import GoogleAnalytics from "@/components/analytics/GoogleAnalytics";
import MetaPixel from "@/components/analytics/MetaPixel";
import GoogleTagManager, { GoogleTagManagerNoScript } from "@/components/analytics/GoogleTagManager";
import MicrosoftClarity from "@/components/analytics/MicrosoftClarity";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <GoogleTagManagerNoScript gtmId={process.env.NEXT_PUBLIC_GTM_ID!} />
        <SessionProvider>
          <CartSync />
          {children}
          <Toaster />
          <GoogleAnalytics gaId={process.env.NEXT_PUBLIC_GA_ID!} />
          <MetaPixel pixelId={process.env.NEXT_PUBLIC_META_PIXEL_ID!} />
          <GoogleTagManager gtmId={process.env.NEXT_PUBLIC_GTM_ID!} />
          <MicrosoftClarity clarityId={process.env.NEXT_PUBLIC_CLARITY_ID!} />
        </SessionProvider>
      </body>
    </html>
  );
}
